name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ثبّت الحزمة + تبع dev (اختبارات/لينت)
          pip install ".[dev]" build
          # في حال عندك whois اختياري (يتجاهل الفشل)
          pip install python-whois || true

      - name: Lint (ruff + isort + black checks)
        run: |
          ruff check .
          isort --check-only .
          black --check .

      - name: Test
        run: |
          pytest -q

      - name: Build package
        run: |
          python -m build
